Eugene/setup fe Integrate with questions API
CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15 pull request #27
Opened 2020-10-07 16:32 UTC by EugeneTeu

#26

2020-10-08 03:18 UTC, AaronCQL requested changes

2020-10-08 03:18 UTC, AaronCQL commented on client/util/types.ts
> +  slug?: string // URL slug, generated by title and _id
`slug` should be a compulsory field - the server API should return a well-defined slug

2020-10-08 03:18 UTC, AaronCQL commented on client/components/api/questions.ts
> +const baseUrl = 'http://localhost:8000/api/questions/'
This URL should be a conditional URL based on `process.env.NODE_ENV` to either point to dev or prod URL. Since the base url of `http://localhost:8000/api` will be used in multiple places, perhaps we can even abstract this base url into a constants declaration somewhere for ease of reference?

```js
// some constants file:
const BASE_URL = process.env.NODE_ENV === "dev" ? "http://localhost:8000/api" : "TODO";
const QUESTIONS_URL = `${BASE_URL}/questions`;
const ANSWERS_URL = `${BASE_URL}/answers`;

// in questions.ts:
import { QUESTIONS_URL } from "...";
// use it as is
```

2020-10-08 03:18 UTC, AaronCQL commented on client/components/api/questions.ts
> +  return await res.json()
I don't think `res.json()` is an asynchronous process - can we remove the `await` here?

2020-10-08 03:18 UTC, AaronCQL commented on README.md
> +- Pagination note: Should accept three parmeters: `page` , `pageSize` , `total` (simple offset based pagination)
Agreed. Let's go with this for v0.1.0 for now, and add filtering later on.

2020-10-08 06:10 UTC, EugeneTeu commented on client/components/api/questions.ts
> +  return await res.json()
https://developer.mozilla.org/en-US/docs/Web/API/Body/json 

fetch api returns a promise i think. I auto convert to async await w one of the plugin

2020-10-08 06:15 UTC, EugeneTeu commented on client/components/api/questions.ts
> +const baseUrl = 'http://localhost:8000/api/questions/'
yeap will abstract this out later

2020-10-10 06:47 UTC, EugeneTeu commented on client/components/api/questions.ts
> +};
@AaronCQL @ziyingli @yiyoupteltd  Not sure how we want to handle the error handling for FE here. I transformed the request from the api like this, the handle (See below)

2020-10-10 06:48 UTC, EugeneTeu commented on client/components/questions/ask-question.tsx
> +      });
This is currently how i handle on this page. Plan to write custom error handler here (similar to middleware in BE, but specific to each page)

2020-10-10 06:50 UTC, EugeneTeu commented on client/components/questions/ask-question.tsx
> +  question?: Question | undefined;
note: Can't recall why i put undefined, but i remember its for something....

2020-10-10 06:51 UTC, EugeneTeu commented on client/components/questions/ask-question.tsx
> +        const markdown = editor.current.getInstance().getMarkdown();
Some type error here can't seem to solve, but works fine for now.

2020-10-10 08:30 UTC, EugeneTeu commented
Can Ignore the points on error handling. Refactored

2020-10-11 07:50 UTC, AaronCQL approved these changes
LGTM

2020-10-11 07:51 UTC, merged