Feat: added pagination to server
CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15 pull request #61
Opened 2020-10-17 19:02 UTC by EugeneTeu

Add pagination for server. Deals with #55

2020-10-18 05:34 UTC, EugeneTeu commented on README.md
> +    "total": 15
Total here is to display to users "10 of 1000" at the bottom of the table

2020-10-18 05:52 UTC, AaronCQL requested changes
Make sure tests pass :smile:

2020-10-18 05:52 UTC, AaronCQL commented on README.md
> +    [
The array is missing the `questions` key

2020-10-18 05:52 UTC, AaronCQL commented on server/src/controllers/questions.ts
> +  if (!page || !pageSize || page < 0 || pageSize < 0) {
No need to check `page < 0` or `pageSize < 0`, the `!page` and `!pageSize` already handles these cases.

2020-10-18 05:52 UTC, AaronCQL commented on server/src/controllers/questions.ts
> +    .skip(page > 0 ? (page - 1) * pageSize : 0)
Likewise for this, no need for the ternary, `page` is guaranteed to be `>= 1`

2020-10-19 01:39 UTC, AaronCQL approved these changes
LGTM

2020-10-19 02:02 UTC, merged