Server chore: Updated Level and Subjects Enum
CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15 pull request #76
Opened 2020-10-21 16:03 UTC by yiyoupteltd

close #41

2020-10-21 16:20 UTC, EugeneTeu submitted a review, later dismissed

2020-10-22 00:04 UTC, AaronCQL requested changes

2020-10-22 00:04 UTC, AaronCQL commented on server/src/utils/constants/Level.ts
> +  SECONDARYNT = "Secondary Normal Technical",
Let's put an `_` between the `secondary` and the next word for better readability.

2020-10-23 01:05 UTC, EugeneTeu commented
@yiyoupteltd pls do the change

2020-10-23 01:16 UTC, yiyoupteltd commented
> @yiyoupteltd pls do the change

Ps doing it now, thanks for the reminder

2020-10-23 01:19 UTC, EugeneTeu commented
yiyoupteltd dismissed EugeneTeu’s stale review via 3b69047 39 seconds ago
sad

2020-10-23 01:19 UTC, EugeneTeu approved these changes

2020-10-23 01:23 UTC, merged