Fuzzy search
CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15 pull request #87
Opened 2020-10-27 13:42 UTC by yiyoupteltd

Searched using $text and $search
Close #55

2020-10-27 14:26 UTC, yiyoupteltd commented on server/src/controllers/questions.ts
> +    return { questions, total };
Abit repetitive here, but couldn't find other ways because getPaginatedQuestions would not be defined outside of if else block

2020-10-27 14:28 UTC, yiyoupteltd commented on server/src/controllers/questions.ts
> +    return { questions, total };
Abit repetitive here, but couldn't find any other way as getPaginatedQuestions would not be defined outside of these if else block

2020-10-27 23:57 UTC, AaronCQL requested changes
Make sure tests are passing

2020-10-27 23:57 UTC, AaronCQL commented on server/src/controllers/questions.ts
> +      .find({ $text: { $search: searchString } })
Try this: `.find(searchString ? { $text: { $search: searchString } } : {})`. Then there is no need for the if-else statement anymore.

2020-10-27 23:57 UTC, AaronCQL commented on server/src/services/database.ts
> +  //.createIndex({ title: "text", markdown: "text" });
Remove this comment

2020-10-31 07:19 UTC, AaronCQL approved these changes
LGTM

2020-10-31 07:19 UTC, merged